#!/system/bin/sh
# Diagnostic - check /var status on this device
NB_DIR="/data/adb/netbird"
export HOME="${NB_DIR}/"

echo "=== /var Diagnosis ==="
echo ""
echo "[1] Does /var exist?"
ls -ld /var 2>&1
echo ""
echo "[2] /var mount info:"
mount | grep -E "^tmpfs on /var|^/dev.*on /var" 2>&1 || echo "  (no mount on /var)"
echo ""
echo "[3] Full mount table (var related):"
mount | grep var 2>&1 || echo "  (nothing)"
echo ""
echo "[4] Root filesystem mount:"
mount | grep "on / type" 2>&1
echo ""
echo "[5] Can we create /var/run?"
mkdir -p /var/run 2>&1 && echo "  YES" || echo "  NO"
echo ""
echo "[6] Can we create /var/run/netbird?"
mkdir -p /var/run/netbird 2>&1 && echo "  YES" || echo "  NO"
echo ""
echo "[7] Can we mount tmpfs on /var/run/netbird?"
mount -t tmpfs -o size=1M tmpfs /var/run/netbird 2>&1 && echo "  YES" || echo "  NO"
echo ""
echo "[8] Can we write to /var/run/netbird?"
echo "test" > /var/run/netbird/test 2>&1 && echo "  YES" && rm -f /var/run/netbird/test || echo "  NO"
echo ""
echo "[9] Try netbird with custom daemon-addr in /data:"
echo "    Testing: netbird service run --daemon-addr unix://${NB_DIR}/run/netbird.sock"
echo ""
echo "[10] Check if netbird supports --daemon-addr:"
netbird service run --help 2>&1 | grep -i "daemon-addr\|socket\|addr" || echo "  (no daemon-addr flag found)"
